require:
    - rubocop-rails
    - rubocop-performance
    - rubocop-rspec

AllCops:
    TargetRubyVersion: 3.2
    NewCops: enable
    Exclude:
        - "db/schema.rb"
        - "node_modules/**/*"
        - "bin/*"
        - "config/**/*"
        - "vendor/**/*"

Layout/LineLength:
    Max: 120
