default: &default
    adapter: postgresql
    encoding: unicode
    pool: 5
    username: postgres.bocnejqudyuwfshoqlfl
    password: <%= ENV['DATABASE_PASSWORD'] %>
    host: aws-0-ap-southeast-1.pooler.supabase.com
    port: 5432
    database: postgres

development:
    <<: *default
    database: quest100_development

test:
    <<: *default
    database: postgres_test

production:
    primary:
        <<: *default
        url: <%= ENV["DATABASE_URL"] %>

    cache:
        <<: *default
        url: <%= ENV["DATABASE_URL"] %>

    queue:
        <<: *default
        url: <%= ENV["DATABASE_URL"] %>

    cable:
        <<: *default
        url: <%= ENV["DATABASE_URL"] %>
