default: &default
    adapter: postgresql
    encoding: unicode
    pool: 5
    username: postgres.bocnejqudyuwfshoqlfl
    password: <%= ENV['DATABASE_PASSWORD'] %>
    host: aws-0-ap-southeast-1.pooler.supabase.com
    port: 5432
    database: postgres

development:
    <<: *default
    database: quest100_development

test:
    <<: *default
    database: quest100

production:
    primary: &primary_production
        <<: *default
        database: quest100_production
        username: quest100
        password: <%= ENV["QUEST100_DATABASE_PASSWORD"] %>
    cache:
        <<: *primary_production
        database: quest100_production_cache
        migrations_paths: db/cache_migrate
    queue:
        <<: *primary_production
        database: quest100_production_queue
        migrations_paths: db/queue_migrate
    cable:
        <<: *primary_production
        database: quest100_production_cable
        migrations_paths: db/cable_migrate
